name: Playwright E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Password@123
          MYSQL_DATABASE: SearchBackend
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -pPassword@123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------ Backend Setup ------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend || true
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start Flask backend
        run: |
          cd backend || true
          python app.py &
          echo $! > backend.pid
        env:
          MYSQL_USER: root
          MYSQL_PASS: Password@123
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DB: SearchBackend
          FLASK_ENV: development
          FLASK_APP: app.py

      - name: Wait for backend
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:5001/health > /dev/null; then
              echo "Backend is up!"
              exit 0
            fi
            echo "Waiting for backend..."
            sleep 5
          done
          echo "Backend did not start in time."
          exit 1

      # ------------------ Frontend Setup ------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: npm ci

        # ADD THIS STEP HERE
      - name: Install Playwright browsers
        run: npx playwright install 

      - name: Build frontend
        run: npm run build

      - name: Start frontend preview
        run: |
          npm run preview &
          echo $! > frontend.pid
        env:
          VITE_API_URL: "http://127.0.0.1:5001"

      - name: Wait for frontend
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:4173 > /dev/null; then
              echo "Frontend is up!"
              exit 0
            fi
            echo "Waiting for frontend..."
            sleep 5
          done
          echo "Frontend did not start in time."
          exit 1

      # ------------------ Run E2E Tests ------------------
      - name: Run Cucumber + Playwright tests
        run: npm run test:e2e
        env:
          NODE_ENV: test
          HEADLESS: true

      # ------------------ Cleanup ------------------
      - name: Stop services
        if: always()
        run: |
          kill $(cat backend.pid) || true
          kill $(cat frontend.pid) || true
