name: SearchBar E2E Tests (no-docker MySQL)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    # Provide values to all steps via env (root password must be set as a repo secret)
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: SearchBackend
      APP_URL: http://localhost:4173

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install OS deps (MySQL server, client, netcat)
        run: |
          sudo apt-get update
          # Noninteractive install so it doesn't prompt
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server default-mysql-client netcat
          sudo systemctl enable mysql || true

      - name: Start MySQL service
        run: |
          sudo service mysql start
          sleep 2
          sudo service mysql status || true

      - name: Secure and set root password + allow TCP auth
        # Use the socket-based sudo mysql initially to set root password and plugin
        run: |
          # Ensure we set the root user to use mysql_native_password and set the provided password.
          # This avoids root using auth_socket and makes password-based TCP access possible.
          sudo mysql <<SQL
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';
          FLUSH PRIVILEGES;
          SQL

      - name: Create client config to avoid passing password on CLI
        run: |
          cat > /tmp/my.cnf <<EOF
[client]
user=root
password=${MYSQL_ROOT_PASSWORD}
host=127.0.0.1
port=3306
EOF
          chmod 600 /tmp/my.cnf

      - name: Wait for MySQL (robust TCP + query check)
        run: |
          echo "Waiting up to 3 minutes for MySQL to accept connections..."
          ready=false
          for i in $(seq 1 36); do
            # Quick TCP port check
            if timeout 1 bash -c "cat < /dev/tcp/127.0.0.1/3306" >/dev/null 2>&1; then
              # Try a simple query using /tmp/my.cnf
              if mysql --defaults-extra-file=/tmp/my.cnf --connect-timeout=5 -e "SELECT 1;" >/dev/null 2>&1; then
                echo "MySQL is ready (attempt $i)."
                ready=true
                break
              else
                echo "TCP open but mysql not responding to queries yet (attempt $i)."
              fi
            else
              echo "127.0.0.1:3306 not open yet (attempt $i)."
            fi
            sleep 5
          done

          if [ "$ready" != "true" ]; then
            echo "ERROR: MySQL did not become available in time."
            sudo journalctl -u mysql --no-pager -n 200 || true
            # Print some status for debugging
            sudo ss -ltnp | grep 3306 || true
            exit 1
          fi

      - name: Setup database and test data
        run: |
          mysql --defaults-extra-file=/tmp/my.cnf --execute="
          CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;
          USE \`${MYSQL_DATABASE}\`;
          CREATE TABLE IF NOT EXISTS item (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(100) NOT NULL
          );
          INSERT IGNORE INTO item (id, name) VALUES 
            (1, 'test item 1'),
            (2, 'test item 2'),
            (3, 'testing'),
            (4, 'tests'),
            (5, 'example test'),
            (201, 'test'),
            (214, 'testing'),
            (215, 'tests'),
            (216, 'test');
          " || (echo "DB setup failed" && sudo journalctl -u mysql --no-pager -n 200 && exit 1)

      - name: Create backend .env file
        run: |
          cat > .env << EOF
          MYSQL_USER=root
          MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
          MYSQL_HOST=127.0.0.1
          MYSQL_PORT=3306
          MYSQL_DB=${MYSQL_DATABASE}
          FLASK_ENV=development
          FLASK_APP=app.py
          EOF

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-sqlalchemy flask-cors python-dotenv pymysql

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright browsers (with deps)
        run: |
          npx playwright install --with-deps chromium

      - name: Start Flask backend
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=development
          # Pass DB envs for your app
          export MYSQL_USER=root
          export MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
          export MYSQL_HOST=127.0.0.1
          export MYSQL_PORT=3306
          export MYSQL_DB=${MYSQL_DATABASE}
          if command -v flask >/dev/null 2>&1; then
            flask run --host=0.0.0.0 --port=5001 &
          else
            python app.py &
          fi
          echo $! > flask.pid

      - name: Wait for Flask backend
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5001/ > /dev/null; then
              echo "Flask backend is ready!"
              break
            fi
            echo "Waiting for Flask backend... ($i/30)"
            sleep 2
          done
          echo "Testing API endpoint (non-fatal):"
          curl -X GET 'http://localhost:5001/api/items?q=test' -H 'Content-Type: application/json' || true

      - name: Build React frontend
        run: npm run build

      - name: Start React frontend (Vite preview)
        run: |
          npm run preview &
          echo $! > react.pid
        env:
          CI: true

      - name: Wait for React frontend
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:4173/ > /dev/null; then
              echo "React frontend is ready!"
              break
            fi
            echo "Waiting for React frontend... ($i/60)"
            sleep 2
          done

      - name: Run Cucumber E2E tests
        run: |
          export HEADLESS=true
          export APP_URL=${{ env.APP_URL }}
          npx cucumber-js --format json:test-results.json --format @cucumber/pretty-formatter
        env:
          NODE_ENV: test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results.json
            test-results/
            screenshots/
            videos/

      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/

      - name: Cleanup processes
        if: always()
        run: |
          if [ -f flask.pid ]; then
            kill $(cat flask.pid) || true
            rm -f flask.pid
          fi
          if [ -f react.pid ]; then
            kill $(cat react.pid) || true
            rm -f react.pid
          fi
          pkill -f "python app.py" || true
          pkill -f "npm run preview" || true

      - name: Show application logs (on failure)
        if: failure()
        run: |
          echo "=== Flask backend root ==="
          curl -s http://localhost:5001/ || echo "Backend not responding"
          echo "=== React frontend root ==="
          curl -s http://localhost:4173/ || echo "Frontend not responding"
          echo "=== MySQL status and last logs ==="
          sudo ss -ltnp | grep 3306 || true
          sudo journalctl -u mysql --no-pager -n 200 || true
          # query DB (uses /tmp/my.cnf to avoid showing password)
          if [ -f /tmp/my.cnf ]; then
            mysql --defaults-extra-file=/tmp/my.cnf --execute="SELECT COUNT(*) as item_count FROM ${MYSQL_DATABASE}.item;" || echo "DB query failed"
          else
            echo "/tmp/my.cnf missing; cannot query DB safely"
          fi
